# Generated by Django 4.2.1 on 2023-05-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number_of_question',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
